'use client';
import React from 'react';
import ReactMarkdown from 'react-markdown';

interface DailyBriefingProps {
  content: string;
  timestamp: string;
}

export const DailyBriefing: React.FC<DailyBriefingProps> = ({ content, timestamp }) => {
  return (
    <div className="bg-terminal-black border border-brand-primary/30 p-4 h-full overflow-y-auto font-mono text-sm shadow-[0_0_15px_rgba(79,70,229,0.1)]">
      <div className="flex items-center justify-between mb-3 border-b border-brand-primary/20 pb-2">
        <h3 className="text-brand-primary font-bold uppercase tracking-wider flex items-center gap-2">
          <span className="animate-pulse">●</span> AI Market Briefing
        </h3>
        <span className="text-xs text-terminal-light-gray opacity-60">
            {new Date(timestamp).toLocaleString()}
        </span>
      </div>
      
      <div className="prose prose-invert prose-sm max-w-none text-terminal-light-gray">
         <ReactMarkdown 
            components={{
                h1: ({node, ...props}) => <h1 className="text-lg font-bold text-white mb-2 border-l-4 border-brand-primary pl-2" {...props} />,
                h2: ({node, ...props}) => <h2 className="text-md font-bold text-brand-secondary mt-4 mb-2" {...props} />,
                strong: ({node, ...props}) => <strong className="text-brand-accent font-semibold" {...props} />,
                ul: ({node, ...props}) => <ul className="list-disc pl-4 space-y-1 my-2" {...props} />,
                li: ({node, ...props}) => <li className="text-terminal-light-gray/90" {...props} />
            }}
         >
             {content}
         </ReactMarkdown>
      </div>
      
      <div className="mt-4 pt-2 border-t border-brand-primary/20 text-[10px] text-terminal-medium-gray text-center uppercase tracking-widest">
          Generated by DeepSeek V3 Intelligence
      </div>
    </div>
  );
};
